name: MileBanks
author: MileKat
main: fr.milekat.banks.Main
version: ${pluginVersion}
api-version: '1.20'
description: "MileBanks: Money management plugin. Tag-based player groups, 
Elasticsearch logs transactions and visualizes detailed history."
website: https://github.com/tutur1004/MileBanks
libraries:
  # Utils
  - com.fasterxml.jackson.core:jackson-databind:2.15.2
  - com.fasterxml.jackson.core:jackson-annotations:2.15.2
  - com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:2.15.2
  # Storage
  - co.elastic.clients:elasticsearch-java:8.13.0
commands:
  money:
    description: "Money management command"
    permission: "mile-banks.admin"
    permission-message: "You can't perform this command"
    usage: /money
    aliases: [bank, banks, money-admin]